In [1]:
# %load c:/bi/bi.py
from scipy.stats import ttest_ind, pearsonr, spearmanr, mannwhitneyu
import warnings
import datetime as dt
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random as rm
import scipy.stats as st
import seaborn as sns

In [2]:
data_row = pd.read_excel("БД урок.xlsx", sheet_name="БД урок")

In [3]:
data = data_row.dropna()
data.head()

,Насколько вам понравился урок?,"Оцените, насколько интересным был урок?",Насколько понятно изложен материал в видео урока?,"Помогли ли вам материалы урока (шпаргалки, конспекты, глоссарии) освоить тему?",Насколько интерактивные упражнения урока помогли вам закрепить полученные знания?,user_id,lesson_name,stream_name,module_name,course
0,Понравился,Интересный,"Понятно, но можно и лучше",Помогли,Помогли,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA
1,"Отчасти понравился, отчасти нет",Интересный,"Отчасти понятно, отчасти нет","Отчасти помогли, отчасти нет",Помогли,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных
2,Понравился,Интересный,Полностью понятно,"Отчасти помогли, отчасти нет",Помогли,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках
3,Очень понравился,Очень интересный,Полностью понятно,Очень помогли,Очень помогли,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность
4,Очень понравился,Очень интересный,Полностью понятно,Очень помогли,Очень помогли,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных

In [4]:
data.describe()

,Насколько вам понравился урок?,"Оцените, насколько интересным был урок?",Насколько понятно изложен материал в видео урока?,"Помогли ли вам материалы урока (шпаргалки, конспекты, глоссарии) освоить тему?",Насколько интерактивные упражнения урока помогли вам закрепить полученные знания?,user_id,lesson_name,stream_name,module_name,course
count,3456,3456,3456,3456,3456,3456,3456,3456,3456,3456
unique,5,6,6,6,6,2101,354,87,68,43
top,Понравился,Интересный,Полностью понятно,Помогли,Помогли,17749859,Урок без имени,Поток без имени,Модуль без имени,Профессия QA
freq,1632,1730,1802,1569,1566,16,812,812,812,594

In [5]:
columns = data.columns.to_list()

In [6]:
columns[0] = 'overall'
columns[1] = 'interesting'
columns[2] = 'clarity'
columns[3] = 'materials'
columns[4] = 'tasks'
columns

['overall',
 'interesting',
 'clarity',
 'materials',
 'tasks',
 'user_id',
 'lesson_name',
 'stream_name',
 'module_name',
 'course']

In [7]:
data.columns = columns
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course
0,Понравился,Интересный,"Понятно, но можно и лучше",Помогли,Помогли,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA
1,"Отчасти понравился, отчасти нет",Интересный,"Отчасти понятно, отчасти нет","Отчасти помогли, отчасти нет",Помогли,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных
2,Понравился,Интересный,Полностью понятно,"Отчасти помогли, отчасти нет",Помогли,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках
3,Очень понравился,Очень интересный,Полностью понятно,Очень помогли,Очень помогли,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность
4,Очень понравился,Очень интересный,Полностью понятно,Очень помогли,Очень помогли,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных

In [8]:
# mask = {'test':2000,'control':1000}
# dataset['cost_group'] = dataset['id_group'].map(mask)

In [9]:
warnings.filterwarnings(action='ignore')

In [10]:
mask_overall  = {'Совсем не понравился' : 1,
                 'Не понравился' : 2,
                 'Отчасти понравился, отчасти нет' : 3, 
                 'Понравился' : 4,
                 'Очень понравился' : 5}
data['overall'] = data['overall'].map(mask_overall).map(float)

In [11]:
mask_interesting = {'Совсем скучный' : 1, 
                    'Неинтересный' : 2, 
                    'Отчасти интересный, отчасти нет' : 3, 
                    'Интересный' : 4, 
                    'Очень интересный' : 5,
                    'Затрудняюсь ответить' : np.nan}
data['interesting'] = data['interesting'].map(mask_interesting)

In [12]:
mask_clarity = {'Совсем непонятно' : 1,
                'Непонятно' : 2, 
                'Отчасти понятно, отчасти нет' : 3, 
                'Понятно, но можно и лучше' : 4, 
                'Полностью понятно' : 5, 
                'Затрудняюсь ответить' : np.nan}
data['clarity'] = data['clarity'].map(mask_clarity)

In [13]:
mask_materials = {'Совсем не помогли' : 1, 
                  'Не помогли' : 2, 
                  'Отчасти помогли, отчасти нет' : 3,
                  'Помогли' : 4, 
                  'Очень помогли' : 5,
                  'Затрудняюсь ответить' : np.nan}
data['materials'] = data['materials'].map(mask_materials)

In [14]:
mask_tasks = {'Совсем не помогли' : 1, 
              'Не помогли' : 2, 
              'Отчасти помогли, отчасти нет' : 3,
              'Помогли' : 4, 
              'Очень помогли' : 5,
              'Затрудняюсь ответить' : np.nan}
data['tasks'] = data['tasks'].map(mask_tasks)

In [15]:
# warnings.resetwarnings()

In [16]:
data

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных
...,...,...,...,...,...,...,...,...,...,...
3545,4.0,4.0,5.0,NaN,4.0,3518631,Урок 1. Основы работы в Excel,Профессия Аналитик данных 30.0,Основы работы в Excel,Профессия Аналитик данных 4.0
3546,4.0,4.0,4.0,4.0,4.0,14768456,27.1 Знакомство с Django,Профессия Python-разработчик 8.0,6. Разработка API на Django,Профессия Python разработчик
3547,4.0,4.0,5.0,3.0,3.0,17830760,Урок без имени,Поток без имени,Модуль без имени,Профессия Полное погружение в маркетинг
3548,3.0,3.0,2.0,2.0,3.0,16063290,10.2 Git / Github / Flask,Профессия Python-разработчик 13.0,3. Основы веб-разработки,Профессия Python разработчик
3549,2.0,3.0,1.0,2.0,2.0,16124788,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA

In [17]:
data.describe()

           overall  interesting      clarity    materials        tasks
count  3456.000000  3419.000000  3399.000000  3231.000000  3244.000000
mean      4.117766     4.124013     4.229185     3.972145     3.978422
std       0.849460     0.796683     0.992091     0.857582     0.894443
min       1.000000     1.000000     1.000000     1.000000     1.000000
25%       4.000000     4.000000     4.000000     4.000000     4.000000
50%       4.000000     4.000000     5.000000     4.000000     4.000000
75%       5.000000     5.000000     5.000000     5.000000     5.000000
max       5.000000     5.000000     5.000000     5.000000     5.000000

In [18]:
data.isnull().sum()

overall          0
interesting     37
clarity         57
materials      225
tasks          212
user_id          0
lesson_name      0
stream_name      0
module_name      0
course           0
dtype: int64

In [19]:
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных

In [20]:
ratings = ['overall', 'interesting', 'clarity', 'materials', 'tasks']

In [21]:
data[ratings].describe()

           overall  interesting      clarity    materials        tasks
count  3456.000000  3419.000000  3399.000000  3231.000000  3244.000000
mean      4.117766     4.124013     4.229185     3.972145     3.978422
std       0.849460     0.796683     0.992091     0.857582     0.894443
min       1.000000     1.000000     1.000000     1.000000     1.000000
25%       4.000000     4.000000     4.000000     4.000000     4.000000
50%       4.000000     4.000000     5.000000     4.000000     4.000000
75%       5.000000     5.000000     5.000000     5.000000     5.000000
max       5.000000     5.000000     5.000000     5.000000     5.000000

In [22]:
data['share45'] = data[ratings[1:5]].isin([4,5]).sum(axis=1) / 4
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course,share45
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA,1.00
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных,0.50
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках,0.75
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность,1.00
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных,1.00

In [23]:
statdictP = dict()
statdictS = dict()
sd = list()
def tolist(x, y):
    '''
    x - data iterable array, 
    y - data iterable array
    '''
    ps, pv = st.pearsonr(x, y)
    pear = [ps, pv]
    ss, sv = st.spearmanr(x, y)
    spea = [ss, sv]
    statdictP['name'] = 'Пирсон'
    statdictP['data'] = pear
    statdictP['level'] = [0.3, 0.7]
    statdictP['alpha'] = 0.05
    statdictS['name'] = 'Спирман'
    statdictS['data'] = spea
    statdictS['level'] = [0.3, 0.7]
    statdictS['alpha'] = 0.05
    sd = [statdictP, statdictS]
    return sd

def power(lst):
    '''
    lst - list
    '''
    for i in range(len(lst)):
        if lst[i]['data'][1] < lst[i]['alpha']:
            nm = lst[i]['name']
            if abs(lst[i]['data'][0]) < lst[i]['level'][0]:
                pwr = 'слабая'
            elif abs(lst[i]['data'][0]) < lst[i]['level'][1]:
                pwr = 'средняя'
            else:
                pwr = 'сильная'
            print(f'Корреляция {nm}а: {pwr}')
        else:
            print(f'Корреляция {nm}а равна нулю')

def proxi_ranges(r1, r2, alpha = 0.05):
    '''
    r1 - data iterable array,
    r2 - data iterable array
    '''
    cov = np.cov(r1, r2)
    print('Ковариация: {:10.2f}'.format(cov[0][1]))
    print()
    print('Дисперсия для метрики 1: {:10.2f}'.format(cov[0][0]))
    print('Дисперсия для метрики 2: {:10.2f}'.format(cov[1][1]))
    print()
    power(tolist(r1, r2))

In [24]:
proxi_ranges(data.dropna().overall, data.dropna().interesting)

Ковариация:       0.48

Дисперсия для метрики 1:       0.64
Дисперсия для метрики 2:       0.61

Корреляция Пирсона: сильная
Корреляция Спирмана: сильная

In [25]:
proxi_ranges(data.dropna().overall, data.dropna().clarity)

Ковариация:       0.47

Дисперсия для метрики 1:       0.64
Дисперсия для метрики 2:       0.92

Корреляция Пирсона: средняя
Корреляция Спирмана: средняя

In [26]:
proxi_ranges(data.dropna().overall, data.dropna().materials)

Ковариация:       0.44

Дисперсия для метрики 1:       0.64
Дисперсия для метрики 2:       0.71

Корреляция Пирсона: средняя
Корреляция Спирмана: средняя

In [27]:
proxi_ranges(data.dropna().overall, data.dropna().tasks)

Ковариация:       0.45

Дисперсия для метрики 1:       0.64
Дисперсия для метрики 2:       0.75

Корреляция Пирсона: средняя
Корреляция Спирмана: средняя

In [28]:
proxi_ranges(data.dropna().overall, data.dropna().share45)

Ковариация:       0.17

Дисперсия для метрики 1:       0.64
Дисперсия для метрики 2:       0.10

Корреляция Пирсона: средняя
Корреляция Спирмана: средняя

In [29]:
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course,share45
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA,1.00
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных,0.50
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках,0.75
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность,1.00
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных,1.00

In [30]:
data['var'] = data[ratings[1:5]].var(axis=1)
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course,share45,var
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA,1.00,0.000000
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных,0.50,0.333333
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках,0.75,0.666667
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность,1.00,0.000000
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных,1.00,0.000000

In [31]:
data.groupby(['overall', 'share45']).agg({'var' : ['count', 'min', 'mean', 'max'],
                                          'interesting' : 'mean',
                                          'clarity' : 'mean',
                                          'materials' : 'mean',
                                          'tasks' : 'mean'})

                  var                               interesting   clarity  \
                count       min      mean       max        mean      mean
overall share45
1.0     0.00       35  0.000000  0.311905  1.333333    1.787879  1.314286
        0.25        9  0.250000  2.500000  4.500000    2.875000  3.200000
        0.50        1  3.000000  3.000000  3.000000    4.000000  4.000000
2.0     0.00       64  0.000000  0.427083  1.333333    2.288136  1.873016
        0.25       18  0.250000  1.847222  4.500000    2.888889  2.882353
        0.50        5  0.333333  1.450000  3.000000    3.200000  4.600000
        0.75        4  0.250000  2.270833  3.583333    2.250000  3.500000
3.0     0.00      137  0.000000  0.207421  1.333333    2.855072  2.691729
        0.25      128  0.250000  0.850260  4.500000    3.379032  3.213115
        0.50       95  0.000000  0.781579  2.916667    3.425532  3.782609
        0.75       68  0.000000  0.549020  1.583333    3.573529  3.867647
        1.00       24  0.000000  0.118056  0.333333    4.041667  4.291667
4.0     0.00       16  0.000000  0.156250  1.000000    3.000000  2.647059
        0.25      118  0.250000  0.638418  3.583333    3.785124  2.991150
        0.50      251  0.000000  0.642762  4.333333    3.856000  3.855422
        0.75      354  0.000000  0.469397  3.000000    3.983051  4.114286
        1.00      886  0.000000  0.165256  0.333333    4.084650  4.556433
5.0     0.00        1  0.000000  0.000000  0.000000    3.000000  3.000000
        0.25        4  0.500000  0.958333  1.333333    4.666667  3.000000
        0.50       57  0.000000  1.048246  3.666667    4.719298  4.226415
        0.75      157  0.000000  0.761677  4.000000    4.448718  4.410256
        1.00      996  0.000000  0.116215  0.333333    4.853414  4.897590

                materials     tasks
                     mean      mean
overall share45
1.0     0.00     1.678571  1.529412
        0.25     2.714286  2.375000
        0.50          NaN  1.000000
2.0     0.00     2.200000  2.137931
        0.25     2.812500  2.933333
        0.50     3.500000  3.000000
        0.75     4.250000  4.250000
3.0     0.00     2.809524  2.701613
        0.25     2.956897  2.938596
        0.50     3.449438  3.321839
        0.75     3.882353  4.015152
        1.00     4.041667  4.125000
4.0     0.00     2.866667  2.733333
        0.25     2.915888  2.886792
        0.50     3.242268  3.393035
        0.75     3.787781  3.840491
        1.00     4.121896  4.120767
5.0     0.00          NaN       NaN
        0.25     3.000000  3.000000
        0.50     3.238095  3.000000
        0.75     4.066176  4.129771
        1.00     4.704819  4.727912

In [38]:
bp = data[ratings[1:5]].isna().sum(axis=1).reset_index().drop('index', axis=1)
bp.columns = ['is_nan']
bp.groupby(['is_nan'])['is_nan'].count()

is_nan
0    3075
1     269
2      84
3      18
4      10
Name: is_nan, dtype: int64

In [34]:
data.head()

,overall,interesting,clarity,materials,tasks,user_id,lesson_name,stream_name,module_name,course,share45,var
0,4.0,4.0,4.0,4.0,4.0,16024429,Инструменты тестирования,Профессия инженер по тестированию 29.0 Професс...,Тестирование API,Профессия QA,1.00,0.000000
1,3.0,4.0,3.0,3.0,4.0,17679376,Урок без имени,Поток без имени,Модуль без имени,Excel для анализа данных,0.50,0.333333
2,4.0,4.0,5.0,3.0,4.0,11265148,Урок без имени,Поток без имени,Модуль без имени,Профессия Маркетинг на международных рынках,0.75,0.666667
3,5.0,5.0,5.0,5.0,5.0,17674079,Урок без имени,Поток без имени,Модуль без имени,Финансовая грамотность,1.00,0.000000
4,5.0,5.0,5.0,5.0,5.0,15970399,Урок 2. Стиль обучения и график обучения,Профессия Аналитик данных 24.0,Soft-track,Профессия Аналитик данных,1.00,0.000000

In [37]:
data.to_csv("data_2_ml.csv", sep=" ", header=True, index=False)